<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="CloudinaryDotNet" Version="1.28.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Hangfire.Core" Version="1.8.23" />
    <PackageReference Include="QuestPDF" Version="2026.2.2" />
    <PackageReference Include="Stripe.net" Version="50.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediCore.DAL\MediCore.DAL.csproj" />
  </ItemGroup>

</Project>
